### Numpy ###
This library is made for the purpose of reducing storage space in the Python language
As we know, the Python library does not have a fixed storage type, so it gives more than what is needed.
<br> <h6>Example : </h6><br>
x = 5 (x allocate 16 bytes)<br>
int x = 5 ( x -> int allocate 4 bytes)

In [205]:
import numpy as np

#### 0. Data Types

### Numpy Data Types
Numpy has the following data types: 
- ```int```
- ```float```
- ```complex```
- ```bool```
- ```string```
- ```unicode```
- ```object```

The numeric data types have various precisions like 32-bit or 64-bit. 

Numpy data types can be represented using either __Type__ or __Type Code__

In [206]:
import numpy as np
import pandas as pd

dtypes = pd.DataFrame({
    'Type': [
        'int8',
        'uint8',
        'int16',
        'uint16',
        'int or int32',
        'uint32',
        'int64',
        'uint64',
        'float16',
        'float32',
        'float or float64',
        'float128',
        'complex64',
        'complex or complex128',
        'bool',
        'object',
        'string_',
        'unicode_',
    ],
    'Type Code': [
        'i1',
        'u1',
        'i2',
        'u2',
        'i4 or i',
        'u4',
        'i8',
        'u8',
        'f2',
        'f4 or f',
        'f8 or d',
        'f16 or g',
        'c8',
        'c16',
        None,
        'O',
        'S',
        'U',
    ]
})

dtypes

Type Type Code
0                    int8        i1
1                   uint8        u1
2                   int16        i2
3                  uint16        u2
4            int or int32   i4 or i
5                  uint32        u4
6                   int64        i8
7                  uint64        u8
8                 float16        f2
9                 float32   f4 or f
10       float or float64   f8 or d
11               float128  f16 or g
12              complex64        c8
13  complex or complex128       c16
14                   bool      None
15                 object         O
16                string_         S
17               unicode_         U

###### so now if u need to allocate data u can choose the dtype to stop roaring memory.
<h5>array(list, dtype = "   ")</h5>

In [ ]:
arr = np.array([1, 2, 3], dtype='f4')
#printing the array
print(arr)
#printing the type
print(arr.dtype)

print()

#u can also put data that python can convert it
# 3.5f -> 3I , '2's -> 2I
arr = np.array([1, '2', 3.5], dtype='i4')
print(arr)
print(arr.dtype)

###### Type Conversion

```astype``` method: convert the data type of an array to other data types. 

Notice that ```astype``` returns a copy of the array instead of converting the data type in place. You need to assign the copy to the original array or a new array.

In [ ]:
arr = np.array([1, 2, 3], dtype='int16')  # 16 / 8 = 2 ==> 2 bytes
print('Original Data Type: ' + str(arr.dtype))

arr = arr.astype(np.float32)
# convert arr type from int16 --> float32 ( 8 bytes )
print('Data Type After Conversion: ' + str(arr.dtype))
arr

__WARNING__: be cautious about data overflow when you downcast the data type (from higher precision to lower precision). Some unexpected and undefined values might occur and it is usually difficult to debug such issues. 

In [ ]:
# An example of integer overflow at downcasting
arr = np.array([126, 127, 129], dtype='int16')

print('np array before type conversion: ' + str(arr))
#print(arr.max())
# Range of int8 [-128, 127], 256 overflows after conversion
arr = arr.astype('int8')
print('np array after type conversion: ' + str(arr))

##### 1. create an array

In [207]:
mylist = [1, 2, 3, 4, 5]
arr = np.array(mylist)

print(arr)
print(mylist)

print(type(mylist))
print(type(arr))

print(arr.dtype)

[1 2 3 4 5]
[1, 2, 3, 4, 5]
<class 'list'>
<class 'numpy.ndarray'>
int32


In [208]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### inspect general information of an array

In [ ]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
print(arr)
print()
print(np.info(arr))

### inspect the data type of an array

In [ ]:
print(arr.dtype)

### inspect the dimension of an array

In [ ]:
print(arr.shape)

### inspect length of an array

In [ ]:
print(len(arr)) # print number of rows 

### inspect the number of dimensions of an array

In [209]:
print(arr.ndim)

1


### inspect the number of elements in an array

In [ ]:
print(arr.size)

### inspect the number of bytes of each element in an array

In [210]:
print(arr.itemsize)  # bytes

4


### inspect the memory size of an array (in byte)

In [211]:
# arr.nbytes = arr.size * arr.itemsize
print(arr.nbytes)
print((arr.nbytes)*8) # bits

40
320


### select an element by row and column indices

In [130]:
arr = np.array(range(100)).reshape((10,10))
print(arr[5][5])
# or more conciselyarr
print(arr[5,5])

55
55


### indexing with slicing

In [131]:
print(arr[1:3, :])

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [132]:
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [ ]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(4,2,2)
print(arr)
print("----------------------")
# equivalent to arr[0,:,:,:]
print(arr[0, ...])
print("----------------------")
print(arr[2:,:,:])

### assign a scalar to a slice by broadcasting

In [133]:
arr[1:3,:] = 10    # or simply arr[1:3]
arr[:,1:] = 100
print(arr)

[[  0 100 100 100 100 100 100 100 100 100]
 [ 10 100 100 100 100 100 100 100 100 100]
 [ 10 100 100 100 100 100 100 100 100 100]
 [ 30 100 100 100 100 100 100 100 100 100]
 [ 40 100 100 100 100 100 100 100 100 100]
 [ 50 100 100 100 100 100 100 100 100 100]
 [ 60 100 100 100 100 100 100 100 100 100]
 [ 70 100 100 100 100 100 100 100 100 100]
 [ 80 100 100 100 100 100 100 100 100 100]
 [ 90 100 100 100 100 100 100 100 100 100]]


### boolean indexing

In [134]:
arr1 = np.arange(25).reshape((5,5))
print(arr1)
print("----------------------------")
bools = np.array([True, True, False, True, False])
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
----------------------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [135]:
# negate the condition
print(arr1[~bools])    

[[10 11 12 13 14]
 [20 21 22 23 24]]


In [136]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
print(arr1[(arr2<2) | (arr2>4)])    

[[ 0  1  2  3  4]
 [20 21 22 23 24]]


### fancy indexing

In [137]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])       

[100 100 100]


In [138]:
# select rows 3,1,2 and columns 6,4,8 
print(arr[[3,1,2]][:, [6,4,8]])    

[[100 100 100]
 [100 100 100]
 [100 100 100]]


### dimension inference

In [139]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)).reshape((4,-1))
print(arr.shape)

(4, 4)


### find elements/indices by conditions

In [140]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [142]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [143]:
print(np.where(arr>5))

(array([1, 1, 2, 2, 2, 2, 3, 3, 3, 3], dtype=int64), array([2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [144]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [145]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]


### Create an aray within specified range
```np.arange()``` method can be used to replace ```np.array(range())``` method

In [ ]:
# np.arange(start, stop, step)
arr = np.arange(0, 10)
print(arr)

### Create an array of evenly spaced numbers within specified range
```np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False)``` has 5 parameters:
- ```start```: start number (inclusive)
- ```stop```: end number (inclusive unless ```endpoint``` set to ```False```)
- ```num_of_elements```: number of elements contained in the array
- ```endpoint```: boolean value representing whether the ```stop``` number is inclusive or not
- ```retstep```: boolean value representing whether to return the step size

In [212]:
arr, arr2 = np.linspace(0,5, 8, endpoint=False, retstep=True)
print(arr)
print(arr.size)
print('The step size is ' + str(arr2))
print ()
arr, arr2 = np.linspace(0,8, 8, endpoint=False, retstep=True)
print(arr)
print(arr.size)
print('The step size is ' + str(arr2))

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]
8
The step size is 0.625

[0. 1. 2. 3. 4. 5. 6. 7.]
8
The step size is 1.0


### Create an array of random values of given shape
```np.random.rand(raw, coloums)``` method returns values in the range [0,1)<br>
```np.random.seed(seed)``` setting seed to make the same random numbers generate always


In [213]:
arr = np.random.seed(66)
arr = np.random.rand(1,5)
print(arr)

# if u want to make it from 1 to 10 just multply by 10
arr = np.random.rand(1,5) * 10
print(arr)

#if u want it as an integer value change the type
arr = arr.astype(np.int32)
print(arr)



[[0.15428758 0.13369956 0.36268547 0.67910888 0.19445006]]
[[2.51210383 7.58416392 5.5761859  5.14802918 4.67799862]]
[[2 7 5 5 4]]


### generate a random sample from a given 1-D array

In [ ]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.3, 0.6]))

##### Create an array of specific value of given shape 
- ```np.zeros()```: create array of all zeros in given shape
- ```np.zeros_like()```: create array of all zeros with the same shape and data type as the given input array
- ```np.ones()```: create array of all ones in given shape
- ```np.ones_like()```: create array of all ones with the same shape and data type as the given input array
- ```np.empty()```: create array of empty values in given shape
- ```np.empty_like()```: create array of empty values with the same shape and data type as the given input array
- ```np.full()```: create array of constant values in given shape
- ```np.full_like()```: create array of constant values with the same shape and data type as the given input array

Notice that the initial values are not necessarily set to zeroes.

They are just some garbage values in random memory addresses.

In [ ]:
arr = np.zeros((2,3))
print(arr)

arr = np.ones((2,5))
print(arr)

arr = np.empty((2,7))
print(arr)

arr = np.full((2,9) , 3)
print(arr)

##### repeating array

In [214]:
# No axis specified, then flatten the input array first and repeat
# Data Augemnation 
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 4)) 

[0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5]


In [ ]:
# An example of repeating along x-axis
print(np.repeat(arr, 4, axis=0)) # row  

In [ ]:
# An example of repeating along y-axis
print(np.repeat(arr, 4, axis=1)) # column  

In [215]:
# Repeat the whole array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


##### diagonal array 

In [216]:
arr = np.random.rand(4,4) * 10
arr = arr.astype(np.int16)
print(arr)
print()
print(np.diag(arr))

[[0 8 2 0]
 [6 9 5 5]
 [6 6 3 0]
 [1 8 0 3]]

[0 9 3 3]


### numerical calculations:
U can make full calculations in ur array

In [32]:
arr = np.zeros((5,5) , dtype ='i2')
print (arr , '\n')

arr = arr + 10
print (arr, '\n')

arr = arr - 5 
print (arr, '\n')

arr = arr * 8
print (arr, '\n')

arr = arr / 4
print (arr, '\n')

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]] 

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]] 

[[40 40 40 40 40]
 [40 40 40 40 40]
 [40 40 40 40 40]
 [40 40 40 40 40]
 [40 40 40 40 40]] 

[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]] 



#####  U can add, substract, multbly two arrays

np.add(arr1, arr2, out=new_arr)

In [30]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,4,6])
new_arr = np.array([0,0,0], dtype = 'float64')

np.add(arr1, arr2, out=new_arr)
print(new_arr)

np.subtract(arr1, arr2, out=new_arr)
print(new_arr)

np.multiply(arr1, arr2, out=new_arr)
print(new_arr)

np.divide(arr1, arr2, out=new_arr)
print(new_arr)


[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


### element-wise logorithm

In [33]:
print(np.exp(arr))

[[22026.46579481 22026.46579481 22026.46579481 22026.46579481
  22026.46579481]
 [22026.46579481 22026.46579481 22026.46579481 22026.46579481
  22026.46579481]
 [22026.46579481 22026.46579481 22026.46579481 22026.46579481
  22026.46579481]
 [22026.46579481 22026.46579481 22026.46579481 22026.46579481
  22026.46579481]
 [22026.46579481 22026.46579481 22026.46579481 22026.46579481
  22026.46579481]]


In [34]:
# natural log ( base e )
print(np.log(arr)) 

[[2.30258509 2.30258509 2.30258509 2.30258509 2.30258509]
 [2.30258509 2.30258509 2.30258509 2.30258509 2.30258509]
 [2.30258509 2.30258509 2.30258509 2.30258509 2.30258509]
 [2.30258509 2.30258509 2.30258509 2.30258509 2.30258509]
 [2.30258509 2.30258509 2.30258509 2.30258509 2.30258509]]


In [35]:
# base 2
print(np.log2(arr))     

[[3.32192809 3.32192809 3.32192809 3.32192809 3.32192809]
 [3.32192809 3.32192809 3.32192809 3.32192809 3.32192809]
 [3.32192809 3.32192809 3.32192809 3.32192809 3.32192809]
 [3.32192809 3.32192809 3.32192809 3.32192809 3.32192809]
 [3.32192809 3.32192809 3.32192809 3.32192809 3.32192809]]


In [36]:
# base 10
print(np.log10(arr))    

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


##### also ur traingle equations

In [42]:
print(np.sin(arr))

print(np.cos(arr))

#also tan, tansh, sinh, cosh and every traingle equation

[[-0.54402111 -0.54402111 -0.54402111 -0.54402111 -0.54402111]
 [-0.54402111 -0.54402111 -0.54402111 -0.54402111 -0.54402111]
 [-0.54402111 -0.54402111 -0.54402111 -0.54402111 -0.54402111]
 [-0.54402111 -0.54402111 -0.54402111 -0.54402111 -0.54402111]
 [-0.54402111 -0.54402111 -0.54402111 -0.54402111 -0.54402111]]
[[-0.83907153 -0.83907153 -0.83907153 -0.83907153 -0.83907153]
 [-0.83907153 -0.83907153 -0.83907153 -0.83907153 -0.83907153]
 [-0.83907153 -0.83907153 -0.83907153 -0.83907153 -0.83907153]
 [-0.83907153 -0.83907153 -0.83907153 -0.83907153 -0.83907153]
 [-0.83907153 -0.83907153 -0.83907153 -0.83907153 -0.83907153]]


### sum along a specified axis

In [47]:
# if axis not specified, calculate the sum of all elements
print(np.sum(arr))

250.0


In [48]:
# sum along the row
print(np.sum(arr, axis=0))    

[50. 50. 50. 50. 50.]


In [49]:
# sum along the column
print(np.sum(arr, axis=1))    

[50. 50. 50. 50. 50.]


In [17]:
print(np.sum(arr))

11.523109618079697


### compute the min and max along a specified axis

In [52]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

10.0
10.0


In [50]:
# calculate min along the row
print(np.min(arr, axis=0))

[10. 10. 10. 10. 10.]


In [51]:
# calculate max along the column
print(np.max(arr, axis=1))    

[10. 10. 10. 10. 10.]


## compute element-wise min and max of two arrays:
###### find the max/min element between the arrays and make new array with it 

In [24]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print()
print(np.minimum(arr1, arr2))

[1 4 5 8 9]

[0 3 3 7 7]


##### spearate the feactional from the integer

In [94]:
newarr = np.array([1.23,])
re , intg  = np.modf(newarr)

# rounding the number to get the accurate reuslt
fraction = round(float(re), 2)
integer = int(intg)
print(fraction)
print(integer)

0.23
1


#####  compute the overall Avreage

In [107]:
arr = np.arange(4, dtype='int16').reshape((2, 2))
arr

array([[0, 1],
       [2, 3]], dtype=int16)

In [108]:
# compute the overall mean
print(np.mean(arr))

1.5


In [109]:
# compute the mean along the row
print(np.mean(arr, axis=0))   

[1. 2.]


In [112]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[0.5 2.5]


### element-wise comparison

In [113]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [119]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]


####  Sorting an Array

In [150]:
arr = (np.arange(25).reshape(5,5))
np.random.shuffle(arr)
arr

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### sort an array along a specified axis

In [153]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))   

# sort along the row in place
arr.sort(axis=0)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


###### flate the array

In [155]:
arr = arr.flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### swap axes

In [156]:
arr1 = np.arange(16).reshape((2,2,4))
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [157]:
print(arr1.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


### append elements to an array
array is not dinamic so the size cant be change so u need to make another array to append

In [158]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [8]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [10]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


### insert elements into an array

In [12]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [13]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [8,2,6])    
print(arr3)

[8 2 6 1 2 3]


### delete elements from an array

In [159]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [160]:
arr

array([1, 2, 3])

In [161]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


### copy an array

if u copyed an array with the normal way u will change the first array
U are just makeing a new key word to call the array

In [163]:
arr = np.array([1,2,3])

arrx = arr

print(arrx) 

arrx[0] = 7

print(arrx)

print(arr)

[1 2 3]
[7 2 3]
[7 2 3]


to make new array u need to follow this method

In [166]:
# the following methods are all deep copy
arr = np.array([1,2,3])
arr1 = np.copy(arr)
# or 
a = arr.copy()
# or 
arr1 = np.array(arr, copy=True)

print(arr1) 

arr1[0] = 7

print(arr1)

print(arr)

[1 2 3]
[7 2 3]
[1 2 3]


### np.concatenate((a, b), axis=)

In [168]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [169]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [170]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### np.vstack((a, b))

In [171]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### np.hstack((a, b))

In [173]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### split an array 

In [174]:
arr = np.random.rand(6,6)
arr

array([[0.93360678, 0.20092073, 0.25260385, 0.770449  , 0.01080724,
        0.99366919],
       [0.88112547, 0.15684954, 0.95258099, 0.71579922, 0.4748768 ,
        0.66739374],
       [0.23700183, 0.23352685, 0.53857022, 0.60846299, 0.14402415,
        0.64474205],
       [0.14191752, 0.75746772, 0.58126662, 0.27383459, 0.65993095,
        0.59060542],
       [0.89166009, 0.96776864, 0.75655507, 0.93360292, 0.51301903,
        0.1625089 ],
       [0.87197661, 0.45368285, 0.21833698, 0.54070938, 0.70933805,
        0.9866479 ]])

In [175]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.93360678, 0.20092073, 0.25260385, 0.770449  , 0.01080724,
        0.99366919],
       [0.88112547, 0.15684954, 0.95258099, 0.71579922, 0.4748768 ,
        0.66739374],
       [0.23700183, 0.23352685, 0.53857022, 0.60846299, 0.14402415,
        0.64474205]]), array([[0.14191752, 0.75746772, 0.58126662, 0.27383459, 0.65993095,
        0.59060542],
       [0.89166009, 0.96776864, 0.75655507, 0.93360292, 0.51301903,
        0.1625089 ],
       [0.87197661, 0.45368285, 0.21833698, 0.54070938, 0.70933805,
        0.9866479 ]])]


In [178]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2[0], '\n\n', arr2[1])

[[0.93360678 0.20092073 0.25260385]
 [0.88112547 0.15684954 0.95258099]
 [0.23700183 0.23352685 0.53857022]
 [0.14191752 0.75746772 0.58126662]
 [0.89166009 0.96776864 0.75655507]
 [0.87197661 0.45368285 0.21833698]] 

 [[0.770449   0.01080724 0.99366919]
 [0.71579922 0.4748768  0.66739374]
 [0.60846299 0.14402415 0.64474205]
 [0.27383459 0.65993095 0.59060542]
 [0.93360292 0.51301903 0.1625089 ]
 [0.54070938 0.70933805 0.9866479 ]]


### Set operations

### select the unique elements from an array

In [179]:
arr = np.array([7,1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6 7]


In [180]:
arr = np.array([7,1,1,2,2,3,3,4,5,6])
x = arr.tolist()
print(type(arr))
print(type(x))
x

<class 'numpy.ndarray'>
<class 'list'>


[7, 1, 1, 2, 2, 3, 3, 4, 5, 6]

In [181]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)

#print(type(uniques))
print(uniques)
#print(type(counts))
print(counts)

x = int(counts[0])
type(x)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


int

### compute the intersection & union of two arrays

In [182]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [183]:
# intersection
print(np.intersect1d(arr1, arr2))
print(type(np.intersect1d(arr1, arr2)))

[3 4 5]
<class 'numpy.ndarray'>


In [184]:
# union
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


In [185]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


In [186]:
np.where(arr1 == 3)

(array([2], dtype=int64),)

### compute whether each element of an array is contained in another

In [187]:
print(np.in1d(arr1, arr2))
# arr1=  1 , 2, ,3 ,4, 5 
# arr2 = 3, 4, 5 , 6 , 7

[False False  True  True  True]


In [188]:
# preserve the shape of the array in the output, if the array is of higher dimensions
print(np.isin(arr1, arr2))

[False False  True  True  True]


### compute the elements in an array that are not in another

In [189]:
print(np.setdiff1d(arr2, arr1))

[6 7]


In [190]:
print(np.setdiff1d(arr1, arr2))

[1 2]


### compute the elements in either of two arrays, but not both

In [191]:
print(np.setxor1d(arr1, arr2))

[1 2 6 7]


#### Marrix Operations

In [192]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

### matrix multiplication

In [193]:
print(arr1.dot(arr2))
# or
print()
print(np.dot(arr1, arr2))
# or
print()
print(arr1 @ arr2)

[[1.45375639 1.80724016 0.78245476 0.35596937 1.79877107]
 [1.14916943 1.20497427 0.58589349 0.29514425 1.25081914]
 [1.00827961 1.17575771 0.67103423 0.37574566 1.4761156 ]
 [1.99913719 2.31358011 1.08152916 0.47427381 2.12204261]
 [1.16871287 1.32960063 0.68016892 0.32849846 1.45516753]]

[[1.45375639 1.80724016 0.78245476 0.35596937 1.79877107]
 [1.14916943 1.20497427 0.58589349 0.29514425 1.25081914]
 [1.00827961 1.17575771 0.67103423 0.37574566 1.4761156 ]
 [1.99913719 2.31358011 1.08152916 0.47427381 2.12204261]
 [1.16871287 1.32960063 0.68016892 0.32849846 1.45516753]]

[[1.45375639 1.80724016 0.78245476 0.35596937 1.79877107]
 [1.14916943 1.20497427 0.58589349 0.29514425 1.25081914]
 [1.00827961 1.17575771 0.67103423 0.37574566 1.4761156 ]
 [1.99913719 2.31358011 1.08152916 0.47427381 2.12204261]
 [1.16871287 1.32960063 0.68016892 0.32849846 1.45516753]]


### QR factorization 

In [194]:
arr = np.random.rand(5,5)

q, r = np.linalg.qr(arr)
print(q)
print(r)

[[-0.53638643  0.66143858  0.12136378  0.11345379 -0.49717973]
 [-0.26482099 -0.72083332  0.18723198  0.10757718 -0.60302612]
 [-0.43890457 -0.13775026 -0.52909939  0.64316381  0.30786651]
 [-0.46873846 -0.11577138 -0.44922258 -0.74833309  0.07125937]
 [-0.47938135 -0.10256794  0.68444716 -0.04351192  0.53787743]]
[[-1.40476893 -0.8607702  -0.74193744 -1.65898899 -0.97312731]
 [ 0.         -0.31279049 -0.27973645 -0.43903205 -0.80592437]
 [ 0.          0.         -0.3497934   0.07498183 -0.40957354]
 [ 0.          0.          0.          0.37246515 -0.23878074]
 [ 0.          0.          0.          0.         -0.28643955]]


### singular value decomposition (SVD)

In [195]:
arr = np.random.rand(5,5)

u, s, v = np.linalg.svd(arr)
print(u)
print(s)
print(v)

[[-0.38264372  0.11184479 -0.3650495  -0.28597894  0.79122022]
 [-0.20520398 -0.38496384  0.5517084  -0.70932039 -0.04665406]
 [-0.46046092 -0.4550735  -0.6051722  -0.06030023 -0.45936298]
 [-0.62369321 -0.17627635  0.43716466  0.60663949  0.14425334]
 [-0.45875662  0.77532467  0.07078406 -0.20840597 -0.37412643]]
[2.86041219 0.85935809 0.49850736 0.07490507 0.05718373]
[[-0.57762707 -0.43974617 -0.43759946 -0.2920023  -0.44295783]
 [ 0.37000242 -0.27966836 -0.68361849 -0.12112389  0.55034405]
 [-0.56309337  0.60981436 -0.1358719  -0.29178512  0.45546962]
 [ 0.08942456  0.49903182 -0.5652042   0.51739831 -0.39473243]
 [-0.45207774 -0.32787591  0.05705705  0.73974596  0.37100339]]


### compute eigen values

In [196]:
arr = np.random.rand(5,5)
print(np.linalg.eigvals(arr))

[ 2.31862775+0.j         -0.61840096+0.j         -0.03292631+0.j
  0.31114279+0.04156932j  0.31114279-0.04156932j]


### eigen value decomposition

In [197]:
arr = np.random.rand(5,5)

w, v = np.linalg.eig(arr)
print(w)    # eigen values
print(v)    # eigen vectors

[ 2.34396056+0.j         -0.23128479+0.40757675j -0.23128479-0.40757675j
  0.45113758+0.j          0.70501946+0.j        ]
[[ 0.45217448+0.j          0.48398763+0.02270665j  0.48398763-0.02270665j
  -0.55216607+0.j         -0.2260468 +0.j        ]
 [ 0.49628097+0.j         -0.65620931+0.j         -0.65620931-0.j
  -0.45901954+0.j          0.06489418+0.j        ]
 [ 0.5828242 +0.j          0.15588691+0.3291169j   0.15588691-0.3291169j
   0.24724055+0.j         -0.46066772+0.j        ]
 [ 0.30569071+0.j         -0.08280731-0.41842004j -0.08280731+0.41842004j
   0.02178065+0.j         -0.28258263+0.j        ]
 [ 0.34075295+0.j          0.10728365+0.09256834j  0.10728365-0.09256834j
   0.6502395 +0.j          0.80785141+0.j        ]]


### compute the trace & determinant

In [198]:
# notice this is not a function in linalg!!!
print(np.trace(arr))    

3.0375480229277634


In [199]:
print(np.linalg.det(arr))

0.16372515753835507


### calculate the inverse/psedo-inverse of a matrix

In [200]:
arr = np.random.rand(5,5)

In [201]:
# compute the inverse of a matrix
print(np.linalg.inv(arr))

[[ 1.04035802 -0.46536373  0.91715191 -1.14405192  0.15881509]
 [-0.42096611  1.3749777   0.81756401 -0.57602363 -1.66391529]
 [-2.62184769 -1.28941025  1.75327332 -0.10513423  1.03412217]
 [ 0.70709271  0.08685397 -0.33558693  1.25357478 -0.73220169]
 [ 1.51922021  1.05582409 -2.40319797  0.65840634  0.91597262]]


In [202]:
# compute the psudo-inverse of a matrix
print(np.linalg.pinv(arr))

[[ 1.04035802 -0.46536373  0.91715191 -1.14405192  0.15881509]
 [-0.42096611  1.3749777   0.81756401 -0.57602363 -1.66391529]
 [-2.62184769 -1.28941025  1.75327332 -0.10513423  1.03412217]
 [ 0.70709271  0.08685397 -0.33558693  1.25357478 -0.73220169]
 [ 1.51922021  1.05582409 -2.40319797  0.65840634  0.91597262]]


### solve a linear system

In [203]:
# solve a linear system in closed form
y = [1,2,3,4,5]
print(np.linalg.solve(arr, y))

[-0.92104593 -5.84198965  4.80922571  1.22733056  3.63476295]
